Testing in ubuntu 22.04

diff --git a/d-i/source/user-setup/user-setup-apply b/d-i/source/user-setup/user-setup-apply
--- a/d-i/source/user-setup/user-setup-apply
+++ b/d-i/source/user-setup/user-setup-apply
@@ -168,6 +168,13 @@ if [ "$RET" = true ] && ! is_system_user; then
 		else
 			$log $chroot $ROOT udevadm settle
 		fi
+		if ! $log $chroot $ROOT ecryptfs-setup-swap -f -n; then
+			echo "ecryptfs-setup-swap failed." >&2
+			db_input critical user-setup/encrypt-home-failed || true
+			db_go || true
+			ENCRYPT_HOME="false"
+			ENCRYPT_HOME_OPT=
+		fi
 		if $umountproc; then
 			$log $chroot $ROOT umount /proc
 		fi
@@ -214,12 +221,12 @@ if [ "$RET" = true ] && ! is_system_user; then
 		if [ -x $ROOT/usr/bin/zsh ] && [ `dpkg-query -W --showformat='${db:Status-Status}' hamonikr-zsh` = "installed" ] ; then
 			$log $chroot $ROOT adduser --disabled-password --shell /usr/bin/zsh --gecos "$RET" $UIDOPT $ENCRYPT_HOME_OPT "$USER" >/dev/null || true
 		else
-			$log $chroot $ROOT adduser --disabled-password --gecos "$RET" $UIDOPT $ENCRYPT_HOME_OPT "$USER" >/dev/null || true
+		$log $chroot $ROOT adduser --disabled-password --gecos "$RET" $UIDOPT $ENCRYPT_HOME_OPT "$USER" >/dev/null || true
 		fi
 	else
 		$log $chroot $ROOT useradd -c "$RET" -m "$USER" $UIDOPT >/dev/null || true
 	fi
-	
+
 	# Clear the user password from the database.
 	db_set passwd/user-password-crypted ''
 	db_set passwd/user-password ''
@@ -386,6 +393,29 @@ autologin-user-timeout=0"
 			$log $chroot $ROOT update-alternatives --set libgksu-gconf-defaults /usr/share/libgksu/debian/gconf-defaults.libgksu-su
 			$log $chroot $ROOT update-gconf-defaults || true
 		fi
+	fi
+	if [ -z "$OVERRIDE_ALREADY_ENCRYPTED_SWAP" ] && \
+	   [ -n "$ENCRYPT_HOME_OPT" ] && [ -e $ROOT/etc/crypttab ]; then
+		# Zero out all encrypted swap partitions.  It is assumed that
+		# passwords are not used beyond this point in the install.
+		# cryptswap0 /dev/sda5 /dev/urandom swap,cipher=aes-cbc-essiv:sha256
+		# Ideally we would set up a new progress bar here, but we're
+		# inside finish-install's and cdebconf doesn't support nested
+		# progress bars.
+		db_progress INFO user-setup/progress/wipe-swap
+		while read name device source options; do
+			if echo "$options" | grep -q "swap"; then
+				if swapoff $device; then
+					if [ ! -b $device ]; then
+						ONE_MEG=$((1024*1024))
+						size=$(($(stat -c %s ${device})/${ONE_MEG}))
+						dd if=/dev/zero of=$device bs=${ONE_MEG} count=$size 2>/dev/null || true
+					else
+						dd if=/dev/zero of=$device bs=16M 2>/dev/null || true
+					fi
+				fi
+			fi
+		done < $ROOT/etc/crypttab
 	fi
 
 else
